# Dependencies
#markdown:				          redcarpet
#highlighter:			          pygments

# Permalinks
permalink:				          pretty
#permalink:                 /blog/:title/

# Setup
title:			             	 'IT IS ALL B3'
tagline:          				'where he writes his head up.'
description:	           	'This is the official blog of Ban, Nguyen Duc, a digital producer by day and a husband, father, dog/cat lover by night.'
meta-keywords:            'ducban.com, www.ducban.com, digital producer, lb, leo burnett vietnam, leo burnett, ducban, duc ban, nguyen duc ban, nguyenducban, anhthu, anh thu, nguyen thi anh thu, mepoc, poc, nhat an, nguyen nhat an, nhatan, husband, father, dog/cat lover'
thumbnail:                /public/uploads/images/2016-12-24-homepage-cover.jpg
url:	           				   http://ducban.com
typekit-code:             'jbo4rqg'
google-tag-manager-code:  'GTM-PM3JTN'
google-site-verification: 'eMMYf8UbhF0iZDXjK_oJh0RtQ1OiaxEaSPIDpIZ1eJ0'

author:
  name:	          				'B3'
  url:          					http://ducban.com
  twitter:                ducban

paginate:				          3
paginate_path:            "blog/page:num"

excerpt_separator:        <!--more-->

gems:                     [jekyll-sitemap]

# Custom vars
