# Dependencies
#markdown:				redcarpet
#highlighter:			pygments

# Permalinks
#permalink:				pretty
permalink:        /blog/:categories/:title/

# Setup
title:					'IT IS ALL B3'
tagline:				'where he writes his head up.'
description:			'This is the official blog of Ban, Nguyen Duc, a digital producer by day and a husband, father, dog/cat lover by night.'
url:					http://ducban.com

author:
  name:					'B3'
  url:					http://ducban.com

paginate:				3
paginate_path: "blog/page:num"

excerpt_separator: <!--more-->

gems:  [jekyll-sitemap]

# Custom vars
